# Generated by Django 5.1.2 on 2024-10-17 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='escreva a categoria')),
                ('palavraDestaque', models.CharField(max_length=50, verbose_name='escreva a palavra destaque')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='escreva o titulo sem as palavras destacadas')),
                ('primeiraDestaque', models.CharField(max_length=50, verbose_name='escreva a primeira palavra destacada')),
                ('segundaDestaque', models.CharField(max_length=50, verbose_name='escreva a segunda palavra destacada')),
                ('terceiraDestaque', models.CharField(max_length=50, verbose_name='escreva a terceira palavra destacada')),
                ('descricao', models.TextField(verbose_name='escreva a descrição')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to='fotos/%d/%m/%Y')),
                ('nomevideo', models.CharField(default='', max_length=50, verbose_name='qual o nome do card')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.categoria')),
            ],
        ),
    ]
