# Generated by Django 5.1.2 on 2024-10-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textinho', models.TextField(verbose_name='escreva o textinho')),
                ('img1', models.ImageField(upload_to='fotos/%d/%m/%Y')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='fotos/%d/%m/%Y')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
