# Generated by Django 5.1.2 on 2024-10-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_video_videos_video_imgvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', verbose_name='escreva o texto')),
                ('imgtextinho', models.ImageField(default='', upload_to='fotos/%d/%m/%Y')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
