# Generated by Django 5.1.2 on 2024-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_textinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinho',
            name='icone',
            field=models.CharField(default='', max_length=50, verbose_name='escreva como é o icone'),
        ),
    ]
