# Generated by Django 5.1.2 on 2024-10-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(default='', max_length=50, verbose_name='Nome do usuário')),
                ('titulo', models.CharField(default='', max_length=50, verbose_name='Título do comentário')),
                ('comentario', models.CharField(default='', max_length=300, verbose_name='Comentário do usuário')),
                ('pessoas_comentando', models.IntegerField(default=0, verbose_name='Pessoas comentando')),
                ('favoritado', models.BooleanField(verbose_name='Favoritado')),
                ('criado_a', models.IntegerField(default=0, verbose_name='Criado a')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50, verbose_name='Nome do topico')),
                ('descricao', models.CharField(default='', max_length=100, verbose_name='Descrição do topico')),
                ('pessoas_discutindo', models.IntegerField(default=0, verbose_name='Pessoas discutindo')),
                ('criado_a', models.IntegerField(default=0, verbose_name='Criado a')),
            ],
        ),
    ]
