# Generated by Django 5.1.2 on 2024-10-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colorir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Digite o nome')),
                ('card', models.ImageField(upload_to='fotos/%d/%m/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='Didatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='qual a materia')),
                ('card', models.ImageField(upload_to='fotos/%d/%m/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='Pais_profs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Lorem ipsum')),
                ('card', models.ImageField(upload_to='fotos/%d/%m/%Y')),
            ],
        ),
    ]
