# Generated by Django 5.1.2 on 2024-10-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais_profs', '0003_alter_categoria_palavradestaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='nomecard',
            field=models.CharField(default='', max_length=50, verbose_name='qual o nome do card'),
        ),
    ]
