# Generated by Django 5.1.2 on 2024-10-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais_profs', '0004_card_nomecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='classe',
            field=models.CharField(default='', max_length=50, verbose_name='qual a classe no css'),
        ),
    ]
